export const CARD_HEIGHT = 64;
export const ROW_GAP = 16;

export const CONNECTOR_WIDTH = 26;
export const ROUND_ONE_CARD_WIDTH = 182;
export const ROUND_TWO_CARD_WIDTH = 158;
export const CONFERENCE_FINALS_CARD_WIDTH = 148;
export const NBA_FINALS_CARD_WIDTH = 154;

export const ROUND_ONE_POSITIONS = [
  0,
  CARD_HEIGHT + ROW_GAP,
  (CARD_HEIGHT + ROW_GAP) * 2,
  (CARD_HEIGHT + ROW_GAP) * 3,
];

export const BRACKET_TOTAL_HEIGHT = ROUND_ONE_POSITIONS[3] + CARD_HEIGHT;

const ROUND_ONE_CENTERS = ROUND_ONE_POSITIONS.map((position) => position + CARD_HEIGHT / 2);

export const ROUND_TWO_POSITIONS = [
  (ROUND_ONE_CENTERS[0] + ROUND_ONE_CENTERS[1]) / 2 - CARD_HEIGHT / 2,
  (ROUND_ONE_CENTERS[2] + ROUND_ONE_CENTERS[3]) / 2 - CARD_HEIGHT / 2,
];

const ROUND_TWO_CENTERS = ROUND_TWO_POSITIONS.map((position) => position + CARD_HEIGHT / 2);

export const CONFERENCE_FINALS_POSITION =
  (ROUND_TWO_CENTERS[0] + ROUND_TWO_CENTERS[1]) / 2 - CARD_HEIGHT / 2;

export const CONFERENCE_FINALS_CENTER = CONFERENCE_FINALS_POSITION + CARD_HEIGHT / 2;

export const NBA_FINALS_POSITION = CONFERENCE_FINALS_CENTER - CARD_HEIGHT / 2;
